In [1]:
import torch
#check GPU availability
gpu_avail = torch.cuda.is_available()
print(f"Is the GPU available? {gpu_avail}")


Is the GPU available? False


In [3]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
print("Device", device)

Device cpu


In [4]:
#Various ways you can perform tensor addition
a = torch.rand(2,2)
print(a)
b = torch.rand(2,2)
c = a + b
d = torch.add(a,b)
#For in-place addition
print(d)

tensor([[0.5436, 0.7102],
        [0.1958, 0.8726]])
tensor([[0.6239, 1.5753],
        [0.6897, 1.5119]])


In [5]:
a.add_(5)

tensor([[5.5436, 5.7102],
        [5.1958, 5.8726]])

In [7]:
print(a)
print(a*b)
print(a.mul(b))

tensor([[5.5436, 5.7102],
        [5.1958, 5.8726]])
tensor([[0.4451, 4.9399],
        [2.5663, 3.7544]])
tensor([[0.4451, 4.9399],
        [2.5663, 3.7544]])


In [9]:
a = torch.rand(10000,10000)
b = torch.rand(10000,10000)
print(a.size)
a.matmul(b)

<built-in method size of Tensor object at 0x000001FDAF3E4860>


tensor([[2500.6526, 2534.9524, 2505.5503,  ..., 2538.6516, 2510.5198,
         2535.9607],
        [2487.9722, 2522.5549, 2501.0579,  ..., 2535.3782, 2518.7620,
         2542.9163],
        [2479.5938, 2496.6060, 2468.1250,  ..., 2505.9551, 2468.2363,
         2507.5857],
        ...,
        [2461.8872, 2495.2700, 2447.9705,  ..., 2499.3330, 2476.0964,
         2493.9070],
        [2475.8931, 2502.5691, 2475.8037,  ..., 2515.6184, 2470.7700,
         2504.0720],
        [2493.0706, 2507.1970, 2495.6414,  ..., 2531.8860, 2500.0298,
         2539.8867]])

In [10]:
import numpy as np
l=[2,3,4,5]
a=np.array(l)

In [11]:
arr=torch.from_numpy(a)
print(arr)

tensor([2, 3, 4, 5], dtype=torch.int32)


In [12]:
f=torch.zeros(2,3,dtype=torch.float64)
print(f)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [13]:
a=torch.tensor([5,6,7],dtype=torch.float)
b=torch.tensor([1,2,3],dtype=torch.float)
print(a+b)

tensor([ 6.,  8., 10.])


In [14]:
torch.add(b,a,out=c)
print(c)

tensor([ 6.,  8., 10.])


C:\Users\ponku\AppData\Local\Temp/ipykernel_12308/571966660.py:1: UserWarning: An output with one or more elements was resized since it had shape [2, 2], which does not match the required output shape [3]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Resize.cpp:24.)
  torch.add(b,a,out=c)


In [15]:
torch.add(a,b).sum()

tensor(24.)

In [16]:
a=torch.tensor([4,5])
b=torch.tensor([2,3])
a.mul(b)

tensor([ 8, 15])

In [17]:
a.dot(b)

tensor(23)

In [18]:
import torch
  
# creating a tensor with random 
# values of dimension 3 X 5 X 2
input_var = torch.randn(3, 5, 2)
  
# print size
print(input_var.size())
  
print(input_var)
  
# dimensions permuted
input_var = input_var.permute(2, 0, 1)
  
# print size
print(input_var.size())
  
print(input_var)

torch.Size([3, 5, 2])
tensor([[[ 0.5646, -0.8539],
         [ 0.7700,  2.0662],
         [ 1.2165,  1.5655],
         [ 0.2742,  0.4507],
         [ 0.1146,  0.7536]],

        [[-0.8311,  0.1493],
         [-1.0231, -0.2218],
         [ 1.5998, -1.8136],
         [-1.2615,  0.2133],
         [-0.9863, -0.8098]],

        [[-0.5289, -0.6246],
         [-1.7633,  1.0251],
         [-0.4062,  0.7923],
         [-2.1302,  0.6096],
         [ 0.3971,  0.5306]]])
torch.Size([2, 3, 5])
tensor([[[ 0.5646,  0.7700,  1.2165,  0.2742,  0.1146],
         [-0.8311, -1.0231,  1.5998, -1.2615, -0.9863],
         [-0.5289, -1.7633, -0.4062, -2.1302,  0.3971]],

        [[-0.8539,  2.0662,  1.5655,  0.4507,  0.7536],
         [ 0.1493, -0.2218, -1.8136,  0.2133, -0.8098],
         [-0.6246,  1.0251,  0.7923,  0.6096,  0.5306]]])


In [28]:
a1=torch.tensor([[5,9],[2,2]],dtype=torch.float32)
a2=torch.tensor([[6,7],[9,10]],dtype=torch.float32)
C=torch.zeros((2,2),dtype=torch.float32)
for i in range(2):
    v=0
    for j in range(2):
        v=torch.dot(a1[i,:],a2[:,j])
        print("a:**",a1[i,:])
        print("b:**",a2[:,j])
        C[i][j]=v
print(C)
print(torch.matmul(a1,a2))
print(a1.mul(a2))
print(torch.inverse(C))

a:** tensor([5., 9.])
b:** tensor([6., 9.])
a:** tensor([5., 9.])
b:** tensor([ 7., 10.])
a:** tensor([2., 2.])
b:** tensor([6., 9.])
a:** tensor([2., 2.])
b:** tensor([ 7., 10.])
tensor([[111., 125.],
        [ 30.,  34.]])
tensor([[111., 125.],
        [ 30.,  34.]])
tensor([[30., 63.],
        [18., 20.]])
tensor([[ 1.4167, -5.2083],
        [-1.2500,  4.6250]])
